#!/bin/bash

testfiles=*.cpp
dependencies="../src/*"

logfile=./testlog
failures=0

for f in $dependencies
do
  g++ -c $f
done

OBJ=./*.o 
  
echo "" >> $logfile
echo $(date) >> $logfile

for f in $testfiles
do
  echo Testing $f
  g++ -o tempexe $f $OBJ -lfftw3 -lm
  ./tempexe > temp
  if ! diff -q "outputs/$f.out" "./temp"  
  then
    echo $f failed && failures=$((failures + 1)) && echo $f failed >> $logfile
  else
    echo $f passed && echo $f passed >> $logfile
  fi
done
echo $failures failed tests

if [ $failures = "0" ]
  then
    echo All Tests Passed >> $logfile
fi

rm temp tempexe $OBJ 
